version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 30
      runas: root
  BeforeInstall:
    - location: install_depend.sh
      timeout: 30
      runas: root
  AfterInstall: 
    - location: after_install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 30
      runas: root
  
   


      # https://kieran.devops-dev.alit.co.za/