version: 0.0
os: linux
files:
  - source: DemoWebsite.html
    destination: /etc/nginx/sites-enabled/
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 30
      runas: root
  AfterInstall: 
    - location: after_install.sh
      timeout: 30
      runas: root

  
   


      # https://kieran.devops-dev.alit.co.za/