version: 0.0
os: linux
files:
  - source: /DemoWebsite.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_depend
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root


      # https://kieran.devops-dev.alit.co.za/