version: 0.2


phases:
  install:
    commands:
      - ls
      - pip install aws-ssm-copy
################SSM copy job
      - aws-ssm-copy 
        --overwrite
        --source-region us-east-1 
        --region eu-west-1 
        KieranWAFSSMPARAM
  build:
    commands:
      - mkdir KieranCDstore
      - cp appspec.yml KieranCDstore
      - cp stop_server.sh KieranCDstore
      - cp after_install.sh KieranCDstore
artifacts:
  base-directory: '.'
  files:
    - "**/*"