AWSTemplateFormatVersion: '2010-09-09'
Description: github-codepipeline

Parameters:
  # GitHubOAuthToken:
  #   Type: String
  #   NoEcho: true
  #   MinLength: 10
  #   MaxLength: 93
  #   AllowedPattern: '[A-Za-z0-9_]*'

  GitHubOwner:
    Type: String
    Default: KieranConradie
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubRepo:
    Type: String
    Default: KieranRepo
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubBranch:
    Type: String
    Default: master
    AllowedPattern: "[A-Za-z0-9-]+"

  ApplicationStackName:
    Type: String
    Default: KieranDemo
    AllowedPattern: "[A-Za-z0-9-]+"
  
  FullRepoId:
    Type: String
    Default: KieranConradie/KieranRepo

  NorthViginiaBucket:
    Type: String
    Default: angeo-nv
  
  KieranArtifactsBucket:
    KieranS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: Kieranartifactbucket
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za


Resources:
  # PipelineArtifactsBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     VersioningConfiguration:
  #       Status: Enabled
  
  KieranCodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: KieranSSMBuild
      ServiceRole: arn:aws:iam::311668141734:role/service-role/Kierancodebuildservicerole
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za
      Artifacts:
        Packaging: NONE
        Type: CODEPIPELINE
      TimeoutInMinutes: 60
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:4.0'
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yaml
      
  KieranWebApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: KieranCodeDeployApp
      ComputePlatform: Server

  KieranWebappDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref KieranWebApp
      ServiceRoleArn: arn:aws:iam::311668141734:role/KieranCDserviceRole
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      DeploymentGroupName: KieranCodeDeployGroup
      Ec2TagFilters:
      - Key: CodeDeploy
        Type: KEY_AND_VALUE
        Value: KieranCD
        

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: KieranPipeLine
      RoleArn: arn:aws:iam::311668141734:role/service-role/AWSCodePipelineServiceRole-eu-west-1-Kieran_pipe1
      ArtifactStores:
        - Region: eu-west-1
          ArtifactStore:
            Location: !Ref KieranArtifactsBucket
            Type: S3
        - Region: us-east-1
          ArtifactStore:
            Location: !Ref NorthViginiaBucket
            Type: S3
      Stages:
      - Name: Source
        Actions:
        - Name: GIT
          InputArtifacts: []
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: 1
            Provider: CodeStarSourceConnection
          OutputArtifacts:
          - Name: SourceArtifact
          Configuration:
            ConnectionArn: arn:aws:codestar-connections:eu-west-1:311668141734:connection/0df4f9d2-c1db-4087-aefc-4f1973c13aac
            BranchName: !Ref GitHubBranch
            OutputArtifactFormat: "CODE_ZIP"
            # PollForSourceChanges: false
            FullRepositoryId: !Ref FullRepoId

      
      - Name: Security
        Actions:
        - Name: SecurityGroups
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn: arn:aws:iam::311668141734:role/kieran_pipeline_role
            StackName: KieranDemoSecurityStack
            TemplatePath: "SourceArtifact::Security.yaml"
          RunOrder: 1
        - Name: WAF
          Region: us-east-1
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn: arn:aws:iam::311668141734:role/kieran_pipeline_role
            StackName: KieranDemoWafStack
            TemplatePath: "SourceArtifact::waf.yaml"
          RunOrder: 1 
      
      - Name: Upload 
        Actions:
            - Name: UploadToS3-CB
              InputArtifacts:
                - Name: SourceArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: S3
              Configuration:
                BucketName: !Ref KieranArtifactsBucket
                Extract: true
              RoleArn: arn:aws:iam::311668141734:role/service-role/AWSCodePipelineServiceRole-eu-west-1-Kieran_pipe1
              RunOrder: 2

      - Name: CodeBuild
        Actions:
        - Name: CodeBuild
          ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          OutputArtifacts:
            - Name: KieranCDstore
          Configuration: 
            ProjectName: !Ref KieranCodeBuildProject
            PrimarySource: SourceArtifact
          RunOrder: 3


      - Name: ApplicationDeploy
        Actions: 
        - Name: Webflowstack
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn: arn:aws:iam::311668141734:role/kieran_pipeline_role
            StackName: !Ref ApplicationStackName
            TemplatePath: "SourceArtifact::webflow.yaml"
          RunOrder: 4
     
      - Name: Deploy
        Actions: 
        - Name: Webapp
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CodeDeploy
            Version: '1'
          InputArtifacts:
            - Name: KieranCDstore
          Configuration:
            # RoleArn: arn:aws:iam::311668141734:role/kieran_pipeline_role
            ApplicationName: !Ref KieranWebApp
            DeploymentGroupName: !Ref KieranWebappDeploymentGroup
          RunOrder: 5
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za
        