AWSTemplateFormatVersion: '2010-09-09'
Description: github-codepipeline

Parameters:
  # GitHubOAuthToken:
  #   Type: String
  #   NoEcho: true
  #   MinLength: 10
  #   MaxLength: 93
  #   AllowedPattern: '[A-Za-z0-9_]*'

  GitHubOwner:
    Type: String
    Default: KieranConradie
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubRepo:
    Type: String
    Default: KieranRepo
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubBranch:
    Type: String
    Default: master
    AllowedPattern: "[A-Za-z0-9-]+"

  ApplicationStackName:
    Type: String
    Default: KieranDemo
    AllowedPattern: "[A-Za-z0-9-]+"
  
  FullRepoId:
    Type: String
    Default: KieranConradie/KieranRepo

  NorthViginiaBucket:
    Type: String
    Default: angeo-nv

Resources:
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  KieranARTS3Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: "*"
          Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref PipelineArtifactsBucket
              - /*
          Action:
          - S3:getObject
          - S3:ListBucket
      Bucket: !Ref PipelineArtifactsBucket

  KieranCodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: KieranSSMBuild
      ServiceRole: arn:aws:iam::311668141734:role/service-role/Kierancodebuildservicerole
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za
      Artifacts:
        Packaging: NONE
        Type: CODEPIPELINE
      TimeoutInMinutes: 60
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:4.0'
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yaml

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: KieranPipeLine
      RoleArn: arn:aws:iam::311668141734:role/service-role/AWSCodePipelineServiceRole-eu-west-1-Kieran_pipe1
      ArtifactStores:
        - Region: eu-west-1
          ArtifactStore:
            Location: !Ref PipelineArtifactsBucket
            Type: S3
        - Region: us-east-1
          ArtifactStore:
            Location: !Ref NorthViginiaBucket
            Type: S3
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          InputArtifacts: []
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: 1
            Provider: CodeStarSourceConnection
          OutputArtifacts:
          - Name: SourceArtifact
          Configuration:
            ConnectionArn: arn:aws:codestar-connections:eu-west-1:311668141734:connection/0df4f9d2-c1db-4087-aefc-4f1973c13aac
            BranchName: !Ref GitHubBranch
            OutputArtifactFormat: "CODE_ZIP"
            # PollForSourceChanges: false
            FullRepositoryId: !Ref FullRepoId

      - Name: Security
        Actions:
        - Name: SecurityGroups
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn: arn:aws:iam::311668141734:role/kieran_pipeline_role
            StackName: KieranDemoSecurityStack
            TemplatePath: "SourceArtifact::Security.yaml"
          RunOrder: 1
        - Name: WAF
          Region: us-east-1
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn: arn:aws:iam::311668141734:role/kieran_pipeline_role
            StackName: KieranDemoWafStack
            TemplatePath: "SourceArtifact::waf.yaml"
          RunOrder: 1 

      - Name: CodeBuild
        Actions:
        - Name: CodeBuild
          ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration: 
            ProjectName: !Ref KieranCodeBuildProject
            PrimarySource: SourceArtifact
          RunOrder: 2


      - Name: ApplicationDeploy
        Actions: 
        - Name: Webflowstack
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn: arn:aws:iam::311668141734:role/kieran_pipeline_role
            StackName: !Ref ApplicationStackName
            TemplatePath: "SourceArtifact::webflow.yaml"
          RunOrder: 3
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za
        