AWSTemplateFormatVersion: '2010-09-09'
Description: github-codepipeline

Parameters:
  # GitHubOAuthToken:
  #   Type: String
  #   NoEcho: true
  #   MinLength: 10
  #   MaxLength: 93
  #   AllowedPattern: '[A-Za-z0-9_]*'

  GitHubOwner:
    Type: String
    Default: KieranConradie
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubRepo:
    Type: String
    Default: KieranRepo
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubBranch:
    Type: String
    Default: master
    AllowedPattern: "[A-Za-z0-9-]+"

  ApplicationStackName:
    Type: String
    Default: KieranDemo
    AllowedPattern: "[A-Za-z0-9-]+"
  
  FullRepoId:
    Type: String
    Default: KieranConradie/KieranRepo

Resources:
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: KieranPipeLine
      RoleArn: arn:aws:iam::311668141734:role/service-role/AWSCodePipelineServiceRole-eu-west-1-Kieran_pipe1
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactsBucket
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          InputArtifacts: []
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: 1
            Provider: CodeStarSourceConnection
          OutputArtifacts:
          - Name: SourceArtifact
          Configuration:
            ConnectionArn: arn:aws:codestar-connections:eu-west-1:311668141734:connection/0df4f9d2-c1db-4087-aefc-4f1973c13aac
            BranchName: !Ref GitHubBranch
            OutputArtifactFormat: "CODE_ZIP"
            # PollForSourceChanges: false
            FullRepositoryId: !Ref FullRepoId
            # OAuthToken: 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
        
      
      - Name: ApplicationDeploy
        Actions:
        - Name: Security
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn: arn:aws:iam::311668141734:role/kieran_pipeline_role
            StackName: KieranDemoSecurityStack
            TemplatePath: "SourceArtifact::Security.yaml"
          RunOrder: 1
        - Name: WAF
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn: arn:aws:iam::311668141734:role/kieran_pipeline_role
            StackName: KieranDemoSecurityStack
            TemplatePath: "SourceArtifact::waf.yaml"
          RunOrder: 2
        - Name: DeployApproval
          ActionTypeId:
            Category: Approval
            Owner: AWS
            Version: "1"
            Provider: Manual
          RunOrder: 3
        - Name: Webflowstack
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: SourceArtifact
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn: arn:aws:iam::311668141734:role/kieran_pipeline_role
            StackName: !Ref ApplicationStackName
            TemplatePath: "SourceArtifact::webflow.yaml"
          RunOrder: 4
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za
        