AWSTemplateFormatVersion: 2010-09-09


Resources:
  SSHP22:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH & http access
      VpcId: vpc-0441f0ed03f0020af
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
        - CidrIp: 102.65.58.60/32
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
    
  PrefixList:
    Type: 'AWS::EC2::PrefixList'
    Properties:
      PrefixListName: Kieranprefixlist
      AddressFamily: "IPv4"
      MaxEntries: 100
      Entries:
        - Cidr: 52.47.139.0/24
        - Cidr: 18.229.220.192/26
        - Cidr: 54.233.255.128/26
        - Cidr: 3.231.2.0/25
        - Cidr: 3.234.232.224/27
        - Cidr: 3.236.169.192/26
        - Cidr: 3.236.48.0/23
        - Cidr: 34.195.252.0/24
        - Cidr: 34.226.14.0/24
        - Cidr: 13.59.250.0/26
        - Cidr: 18.216.170.128/25
        - Cidr: 3.128.93.0/24
        - Cidr: 3.134.215.0/24
        - Cidr: 52.15.127.128/26
        - Cidr: 3.101.158.0/23
        - Cidr: 52.52.191.128/26
        - Cidr: 34.216.51.0/25
        - Cidr: 34.223.12.224/27
        - Cidr: 34.223.80.192/26
        - Cidr: 35.162.63.192/26
        - Cidr: 35.167.191.128/26
        - Cidr: 44.227.178.0/24
        - Cidr: 44.234.108.128/25
        - Cidr: 44.234.90.252/30
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za

  KieranALBSecGrp:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow Port 80 and 443
      VpcId: vpc-0441f0ed03f0020af
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourcePrefixListId: !Ref PrefixList

Outputs:
  EC2SecGroup:
    Value: !Ref SSHP22
    Description: Import EC2 security group
    Export:
      Name:
        ec2sec
   

  ALBSecGroup:
    Value: !Ref KieranALBSecGrp
    Description: Import ALB security group
    Export:
      Name:
        albsec

  
   