AWSTemplateFormatVersion: 2010-09-09


Resources:
  SSHP22:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH & http access
      VpcId: vpc-0441f0ed03f0020af
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
        - CidrIp: 102.65.58.60/32
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
    
  PrefixList:
    Type: 'AWS::EC2::PrefixList'
    Properties:
      PrefixListName: Kieranprefixlist
      AddressFamily: "IPv4"
      MaxEntries: 100
      Entries:
        - Cidr: 52.47.139.0/24
        - Cidr: 18.229.220.192/26
        # - Cidr: 120.52.22.96/27
        # - Cidr: 205.251.249.0/24
        # - Cidr: 180.163.57.128/26
        # - Cidr: 204.246.168.0/22
        # - Cidr: 111.13.171.128/26 
        # - Cidr: 18.160.0.0/15 
        # - Cidr: 205.251.252.0/23 
        # - Cidr: 54.192.0.0/16
        # - Cidr: 204.246.173.0/24
        # - Cidr: 54.230.200.0/21
        # - Cidr: 120.253.240.192/26
        # - Cidr: 116.129.226.128/26
        # - Cidr: 130.176.0.0/17
        # - Cidr: 108.156.0.0/14 
        # - Cidr: 99.86.0.0/16 
        # - Cidr: 205.251.200.0/21 
        # - Cidr: 223.71.71.128/25 
        # - Cidr: 13.32.0.0/15 
        # - Cidr: 120.253.245.128/26 
        # - Cidr: 13.224.0.0/14 
        # - Cidr: 70.132.0.0/18 
        # - Cidr: 15.158.0.0/16 
        # - Cidr: 111.13.171.192/26 
        # - Cidr: 13.249.0.0/16 
        # - Cidr: 18.238.0.0/15 
        # - Cidr: 18.244.0.0/15 
        # - Cidr: 205.251.208.0/20 
        # - Cidr: 65.9.128.0/18 
        # - Cidr: 130.176.128.0/18 
        # - Cidr: 58.254.138.0/25 
        # - Cidr: 54.230.208.0/20 
        # - Cidr: 3.160.0.0/14 
        # - Cidr: 116.129.226.0/25 
        # - Cidr: 52.222.128.0/17 
        # - Cidr: 18.164.0.0/15 
        # - Cidr: 111.13.185.32/27 
        # - Cidr: 64.252.128.0/18 
        # - Cidr: 205.251.254.0/24 
        # - Cidr: 54.230.224.0/19 
        # - Cidr: 71.152.0.0/17 
        # - Cidr: 216.137.32.0/19 
        # - Cidr: 204.246.172.0/24 
        # - Cidr: 18.172.0.0/15 
        # - Cidr: 120.52.39.128/27 
        # - Cidr: 118.193.97.64/26 
        # - Cidr: 223.71.71.96/27 
        # - Cidr: 18.154.0.0/15 
        # - Cidr: 54.240.128.0/18 
        # - Cidr: 205.251.250.0/23 
        # - Cidr: 180.163.57.0/25 
        # - Cidr: 52.46.0.0/18 
        # - Cidr: 223.71.11.0/27 
        # - Cidr: 52.82.128.0/19 
        # - Cidr: 54.230.0.0/17 
        # - Cidr: 54.230.128.0/18 
        # - Cidr: 54.239.128.0/18 
        # - Cidr: 130.176.224.0/20 
        # - Cidr: 36.103.232.128/26 
        # - Cidr: 52.84.0.0/15
        # - Cidr: 143.204.0.0/16
        # - Cidr: 144.220.0.0/16 
        # - Cidr: 120.52.153.192/26 
        # - Cidr: 119.147.182.0/25 
        # - Cidr: 120.232.236.0/25
        # - Cidr: 111.13.185.64/27
        # - Cidr: 54.182.0.0/16 
        # - Cidr: 58.254.138.128/26 
        # - Cidr: 120.253.245.192/27 
        # - Cidr: 54.239.192.0/19 
        # - Cidr: 18.68.0.0/16
        # - Cidr: 18.64.0.0/14
        # - Cidr: 120.52.12.64/26 
        # - Cidr: 99.84.0.0/16
        # - Cidr: 130.176.192.0/19 
        # - Cidr: 52.124.128.0/17 
        # - Cidr: 204.246.164.0/22 
        # - Cidr: 13.35.0.0/16
        # - Cidr: 204.246.174.0/23
        # - Cidr: 36.103.232.0/25
        # - Cidr: 119.147.182.128/26 
        # - Cidr: 118.193.97.128/25
        # - Cidr: 120.232.236.128/26 
        # - Cidr: 204.246.176.0/20 
        # - Cidr: 65.8.0.0/16
        # - Cidr: 65.9.0.0/17
        # - Cidr: 108.138.0.0/15
        # - Cidr: 120.253.241.160/27 
        # - Cidr: 64.252.64.0/18
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za

  KieranALBSecGrp:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow Port 80 and 443
      VpcId: vpc-0441f0ed03f0020af
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourcePrefixListId: !Ref PrefixList

Outputs:
  EC2SecGroup:
    Value: !Ref SSHP22
    Description: Import EC2 security group
    Export:
      Name:
        ec2sec
   

  ALBSecGroup:
    Value: !Ref KieranALBSecGrp
    Description: Import ALB security group
    Export:
      Name:
        albsec

  
   