AWSTemplateFormatVersion: 2010-09-09


Resources:
  SSHP22:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH & http access
      VpcId: vpc-0441f0ed03f0020af
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
        - CidrIp: 102.65.58.60/32
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
    
  # PrefixList:
  #   Type: 'AWS::EC2::PrefixList'
  #   Properties:
  #     PrefixListName: Kieranprefixlist
  #     AddressFamily: "IPv4"
  #     MaxEntries: 50
  #     Entries:
  #       - Cidr: 13.113.196.64/26 
  #       - Cidr: 13.124.199.0/24	
  #       - Cidr: 130.176.0.0/18	
  #       - Cidr: 130.176.128.0/21	
  #       - Cidr: 130.176.136.0/23	
  #       - Cidr: 130.176.140.0/22	
  #       - Cidr: 130.176.144.0/20	
  #       - Cidr: 130.176.160.0/19	
  #       - Cidr: 130.176.192.0/19	
  #       - Cidr: 130.176.64.0/21	
  #       - Cidr: 130.176.72.0/22	
  #       - Cidr: 130.176.76.0/24	
  #       - Cidr: 130.176.78.0/23	
  #       - Cidr: 130.176.80.0/22	
  #       - Cidr: 130.176.86.0/23	
  #       - Cidr: 130.176.88.0/21	
  #       - Cidr: 130.176.96.0/19	
  #       - Cidr: 15.158.0.0/16	
  #       - Cidr: 18.68.0.0/16	
  #       - Cidr: 204.246.166.0/24	
  #       - Cidr: 205.251.218.0/24	
  #       - Cidr: 52.46.0.0/22	
  #       - Cidr: 52.46.16.0/20	
  #       - Cidr: 52.46.32.0/19	
  #       - Cidr: 52.46.4.0/23	
  #       - Cidr: 52.82.128.0/23	
  #       - Cidr: 52.82.134.0/23	
  #       - Cidr: 54.182.128.0/20	
  #       - Cidr: 54.182.144.0/21	
  #       - Cidr: 54.182.154.0/23	
  #       - Cidr: 54.182.156.0/22	
  #       - Cidr: 54.182.160.0/21	
  #       - Cidr: 54.182.172.0/22	
  #       - Cidr: 54.182.176.0/21	
  #       - Cidr: 54.182.184.0/22	
  #       - Cidr: 54.182.188.0/23	
  #       - Cidr: 54.182.224.0/21	
  #       - Cidr: 54.182.240.0/21	
  #       - Cidr: 54.182.248.0/22	
  #       - Cidr: 54.239.134.0/23	
  #       - Cidr: 54.239.170.0/23	
  #       - Cidr: 54.239.204.0/22	
  #       - Cidr: 54.239.208.0/21	
  #       - Cidr: 64.252.128.0/18	
  #       - Cidr: 64.252.64.0/18	
  #       - Cidr: 70.132.0.0/18
  #     Tags:
  #       - Key: OWNER
  #         Value: Kieran@al.co.za

  KieranALBSecGrp:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow Port 80 and 443
      VpcId: vpc-0441f0ed03f0020af
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

Outputs:
  EC2SecGroup:
    Value: !Ref SSHP22
    Description: Import EC2 security group
    Export:
      Name:
        ec2sec
   

  ALBSecGroup:
    Value: !Ref KieranALBSecGrp
    Description: Import ALB security group
    Export:
      Name:
        albsec

  
   