AWSTemplateFormatVersion: 2010-09-09


Resources:
  SSHP22:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH & http access
      VpcId: vpc-0441f0ed03f0020af
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
        - CidrIp: 102.65.58.60/32
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
    
  PrefixList:
    Type: 'AWS::EC2::PrefixList'
    Properties:
      PrefixListName: Kieranprefixlist
      AddressFamily: "IPv4"
      MaxEntries: 10
      Entries:
        - Cidr: 3.234.232.224/27 3.234.232.224/27
          Description: "us-east-1"
        - Cidr: 3.234.232.224/27
          Description: "us-east-1.2"
        - Cidr: 18.200.212.0/23 52.212.248.0/26
          Description: "eu-west-1"
        - Cidr: 52.212.248.0/26
          Description: "eu-west-1.2"
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za

  KieranALBSecGrp:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow Port 80 and 443
      VpcId: vpc-0441f0ed03f0020af
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourcePrefixListId: !Ref PrefixList

Outputs:
  EC2SecGroup:
    Value: !Ref SSHP22
    Description: Import EC2 security group
    Export:
      Name:
        ec2sec
   

  ALBSecGroup:
    Value: !Ref KieranALBSecGrp
    Description: Import ALB security group
    Export:
      Name:
        albsec

  
   