AWSTemplateFormatVersion: 2010-09-09

Resources:
  SSHP22:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH & http access
      VpcId: vpc-0441f0ed03f0020af
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  KieranALBSecGrp:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow Port 80 and 443
      VpcId: vpc-0441f0ed03f0020af
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  KieranWAF:
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      DefaultAction:
        Allow: {}
      Description: Kieran WAF.
      Name: KieranWAF
      Rules:
        - Action:
            Block: {}
          Name: CustomRulesStringMatchRuleSet
          Priority: 0
          Statement:
            OrStatement:
              Statements:
                - ByteMatchStatement:
                    FieldToMatch:
                      UriPath: {}
                    PositionalConstraint: CONTAINS
                    SearchStringBase64: L2xpYnMvZ3Jhbml0ZS9jc3JmL3Rva2VuLmpzb24=
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
                - ByteMatchStatement:
                    FieldToMatch:
                      UriPath: {}
                    PositionalConstraint: CONTAINS
                    SearchStringBase64: L2xpYnMv
                    TextTransformations:
                      - Priority: 0
                        Type: LOWERCASE
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: CustomRulesStringMatchRuleSet
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
        - Name: AWSManagedRulesSQLiRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesSQLiRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
      Scope: REGIONAL
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: KieranWAF
        SampledRequestsEnabled: true

Outputs:
  EC2SecGroup:
    Value: !Ref SSHP22
    Description: Import EC2 security group
    Export:
      Name:
        ec2sec
   

  ALBSecGroup:
    Value: !Ref KieranALBSecGrp
    Description: Import ALB security group
    Export:
      Name:
        albsec

  WAF:
    Description: Web ACL ID
    Value: !GetAtt 
      - KieranWAF
      - Id
    Export:
      Name:
        webacl
   