AWSTemplateFormatVersion: 2010-09-09

Resources:
  WAFAclArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: KieranWAFSSMPARAM
      Type: String
      Value: !GetAtt KieranWAF.Arn
      Tags:
      - Key: OWNER
        Value: Kieran@al.co.za

  KieranWAF:
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za
      DefaultAction:
        Allow: {}
      Description: Kieran WAF.
      Name: KieranWAF
      Rules:
        - Action:
            Block: {}
          Name: CustomRulesStringMatchRuleSet
          Priority: 0
          Statement:
            OrStatement:
              Statements:
                - ByteMatchStatement:
                    FieldToMatch:
                      UriPath: {}
                    PositionalConstraint: CONTAINS
                    SearchStringBase64: L2xpYnMvZ3Jhbml0ZS9jc3JmL3Rva2VuLmpzb24=
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
                - ByteMatchStatement:
                    FieldToMatch:
                      UriPath: {}
                    PositionalConstraint: CONTAINS
                    SearchStringBase64: L2xpYnMv
                    TextTransformations:
                      - Priority: 0
                        Type: LOWERCASE
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: CustomRulesStringMatchRuleSet
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
        - Name: AWSManagedRulesSQLiRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesSQLiRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
      Scope: CLOUDFRONT 
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: KieranWAF
        SampledRequestsEnabled: true
      
WAFAclArn:
  Type: AWS::SSM::Parameter
  Properties:
    Name: KieranWAFSSMPARAM
    Type: String
    Value: !GetAtt KieranWAF.Arn
    Tags:
    - Key: OWNER
      Value: Kieran@al.co.za

Outputs:
  WAF:
    Description: Web ACL ID
    Value: !GetAtt 
      - KieranWAF
      - Id
    Export:
      Name:
        webacl