
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PubSubnets:
    Type: String
    Default: subnet-011c03bcc5bc7c71d
  KieranCDNcert:
    Type: String
    Default: arn:aws:acm:us-east-1:311668141734:certificate/318b8b77-afd0-4a57-b4e5-b9eae509d4b2
  KieranALBcert:
    Type: String
    Default: arn:aws:acm:eu-west-1:311668141734:certificate/9b7a4dfc-9a0a-43eb-8237-0b4390bff972
  R53HZ:
    Type: String
    Default: devops-dev.alit.co.za.
  KieranCDNaliases:
    Type: String
    Default: kieran.devops-dev.alit.co.za
  # KieranWebACLID:
  #   Type: String
  #   Default: !ImportValue webacl 
  #   # b29458c7-7fba-4f68-9fb8-e56f37c97168
        # arn:aws:wafv2:eu-west-1:311668141734:regional/webacl/KieranWAF/6fce13f0-62a6-46dd-9b83-478df7499515
    
    # lets try it one more time
    #arn:aws:sts::311668141734:assumed-role/Kierancodebuildservicerole/AWSCodeBuild-161d550a-36bb-4903-94d5-09302d955db3

Resources: 

  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: KieranALB
      Scheme: internet-facing
      SecurityGroups: 
      - !ImportValue albsec
      Subnets: 
      - subnet-011c03bcc5bc7c71d
      - subnet-082750b5ae21a79d0
      Tags: 
        - Key: OWNER
          Value: Kieran@al.co.za
      Type: application

  ALBListener:    
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref AppLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref KieranALBcert

  ALBTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckEnabled: true
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 4
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-399
      Name: KieranTG
      Port: 80
      Protocol: HTTP
      Targets:
        - Id: !Ref KieranEc2
          Port: 80
      VpcId: vpc-0441f0ed03f0020af
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za

  # ALBListenerRule:
  #   Type: AWS::ElasticLoadBalancingV2::ListenerRule
  #   Properties:
  #     ListenerArn: !Ref ALBListener
  #     Priority: 1
  #     Conditions:
  #       - Field: headers
  #         HostHeaderConfig:
  #           Values:
  #             - kieran.devops-dev.alit.co.za
  #     Actions:
  #       - Type: forward
  #         Order: 1
  #         TargetGroupArn: !Ref ALBTargetGroup

  KieranCDN:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        WebACLId: '{{resolve:ssm:KieranWAFSSMPARAM}}'
        Comment: 'Kieran Cloudfront Distribution'
        Origins:
          - DomainName: !GetAtt
              - AppLoadBalancer
              - DNSName
            Id: AppLoadBalancer
          # - DomainName: !GetAtt
          #     - AppLoadBalancer
          #     - DNSName
          #   Id: AppLoadBalancer
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: 'match-viewer'
              OriginKeepaliveTimeout: 60
              OriginReadTimeout: 30
              OriginSSLProtocols:
                - TLSv1
                - TLSv1.1
                - TLSv1.2
                - SSLv3
        Enabled: true
        HttpVersion: 'http2'
        Aliases:
          - !Ref 'KieranCDNaliases'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - DELETE
            - OPTIONS
            - PATCH
            - POST
            - PUT
          Compress: false
          DefaultTTL: 31536000
          MaxTTL: 31536000
          MinTTL: 0
          TargetOriginId: AppLoadBalancer
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
            Headers:
              - '*'
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref KieranCDNcert
          SslSupportMethod:  sni-only

  KieranR53:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        DNSName: !GetAtt 
          - KieranCDN
          - DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: !Ref R53HZ
      Name: !Ref KieranCDNaliases
      Type: A  
  
  KieranS3:
    Type: AWS::S3::Bucket
    Properties:
      # AccessControl: Private
      # PublicAccessBlockConfiguration:
      #   BlockPublicAcls: true
      #   BlockPublicPolicy: true
      #   IgnorePublicAcls: true
      #   RestrictPublicBuckets: true
      BucketName: kierans3bucket
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za

  KieranS3Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: "*"
          Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref KieranS3
              - /*
          Action:
          - S3:*
      Bucket: !Ref KieranS3




  KieranLaunchTemp:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: KieranLC
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: ami-0ee415e1b8b71305f
        KeyName: KieranKP 
        IamInstanceProfile:
          Arn:
            Fn::GetAtt:
            - KieranIamInstanceProfile
            - Arn
        NetworkInterfaces:
          - Groups: 
            - !ImportValue ec2sec
            AssociatePublicIpAddress: true
            DeviceIndex: 0
            DeleteOnTermination: true
            SubnetId: !Ref PubSubnets
        UserData: 
          'Fn::Base64': |
            #!/bin/bash -xe
            sudo yum update -y
            sudo amazon-linux-extras install nginx1 -y
            sleep 30
            sudo systemctl start nginx
            sudo yum install ruby wget -y
            sudo wget -P /home/ec2-user/ https://aws-codedeploy-eu-west-1.s3.eu-west-1.amazonaws.com/latest/install
            sudo chmod +x /home/ec2-user/install
            sudo /home/ec2-user/./install auto
            sudo service codedeploy-agent start
        TagSpecifications:
          - ResourceType: volume
            Tags:
              - Key: OWNER
                Value: Kieran@al.co.za
          - ResourceType: instance
            Tags:
              - Key: OWNER
                Value: Kieran@al.co.za
              - Key: CodeDeploy
                Value: KieranCD

  KieranRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSCodeDeployFullAccess
        - arn:aws:iam::aws:policy/IAMUserSSHKeys
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za

  KieranEc2:
    Type: 'AWS::EC2::Instance'
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref KieranLaunchTemp
        Version: !GetAtt 
          - KieranLaunchTemp
          - LatestVersionNumber
      Tags:
        - Key: OWNER
          Value: Kieran@al.co.za
        
  KieranIamInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref KieranRole

